# Language of testing
language: guppy
# LLM models to use for generation of quantum programs
models:
  - deepseek/deepseek-v4-flash
  # - anthropic/claude-haiku-4-5
  # - openai/gpt-5-mini
  # - openai/gpt-5.4-nano

n_programs: 2
n_fixing_cycles: 3
enable_mutation: false
n_mutations: 2
mutation_fix_cycles: 1
max_workers: 10
n_assemble: 2
n_circuits_per_assembly: 2
verbose: false
reasoning_effort: high
ks_low_threshold: 0.0001


# Improvement loop parameters for improving prompt before mass generation
improve_prompt: false
improver_model: deepseek/deepseek-v4-pro
