language: qiskit
models:
  - deepseek/deepseek-v4-flash

n_programs: 2
n_fixing_cycles: 2
max_workers: 10
n_assemble: 2
n_circuits_per_assembly: 2
verbose: false
reasoning_effort: high
ks_low_threshold: 0.001

# Improvement loop parameters for improving prompt before mass generation
improve_prompt: false
improver_model: deepseek/deepseek-reasoner
